small_apps:
  - name: Spark
    id: "1176895641"
  - name: LINE
    id: "539883307"
  - name: Total Video Converter Pro
    id: "426654691"
  - name: ToyViewer
    id: "414298354"
  - name: LadioCast
    id: "411213048"
  - name: Microsoft PowerPoint
    id: "462062816"
  - name: Microsoft Word
    id: "462054704"
  - name: Microsoft Excel
    id: "462058435"
  - name: Keynote
    id: "409183694"
  - name: Pages
    id: "409201541"
  - name: Numbers
    id: "409203825"
