preferences:
  ## Global settings
  - domain: "NSGlobalDomain"
    configures:
    - key: AppleLanguages
      type: array
      value:
        - en-JP
        - ja-JP
        - en
        - ja
    - key: AppleActionOnDoubleClick
      type: string
      value: Minimize
    - key: AppleShowScrollBars
      type: string
      value: WhenScrolling
    - key: AppleShowAllExtensions
      type: bool
      value: yes
    - key: com.apple.keyboard.fnState
      type: bool
      value: yes
    - key: com.apple.trackpad.forceClick
      type: bool
      value: no
    - key: com.apple.trackpad.scaling
      type: int
      value: 2
      
  - domain: "com.apple.AppleMultitouchTrackpad"
    configures:
    - key: Clicking
      type: bool
      value: yes
    - key: TrackpadThreeFingerDrag
      type: bool
      value: yes
    - key: TrackpadThreeFingerTapGesture
      type: int
      value: 2
    - key: TrackpadRightClick
      type: bool
      value: yes
    - key: TrackpadFourFingerHorizSwipeGesture
      type: int
      value: 2
    - key: TrackpadFourFingerPinchGesture
      type: int
      value: 2

  - domain: "com.apple.dock"
    configures:
    - key: orientation
      type: string
      value: "left"
    - key: autohide
      type: bool
      value: yes
    - key: mineffect
      type: string
      value: "scale"
    - key: expose-group-apps
      type: bool
      value: yes
    - key: minimize-to-application
      type: bool
      value: yes
    - key: titlesize
      type: int
      value: 64
    - key: wvous-bl-corner
      type: int
      value: 5 # screen saver
    - key: wvous-bl-modifire
      type: int
      value: 0
    - key: wvous-br-corner
      type: int
      value: 10 # display sleep
    - key: wvous-br-modifire
      type: int
      value: 0
    - key: wvous-tr-corner
      type: int
      value: 10 # display sleep
    - key: wvous-tr-modifire
      type: int
      value: 0

  - domain: "com.apple.finder"
    configures:
    - key: ShowExternalHardDrivesOnDesktop
      type: bool
      value: yes
    - key: ShowHardDrivesOnDesktop
      type: bool
      value: no
    - key: ShowMountedServerOnDesktop
      type: bool
      value: yes
    - key: ShowRemovableMediaOnDesktop
      type: bool
      value: no
    - key: ShowStatusBar
      type: bool
      value: yes
    - key: ShowPathbar
      type: bool
      value: yes

  - domain: "com.apple.screencapture"
    configures:
    - key: location
      type: string
      value: "~/Dropbox/var/ScreenCapture"
    - key: name
      type: string
      value: ""

  - domain: "com.apple.Safari.SandboxBroker"
    configures:
    - key: ShowDevelopMenu
      type: bool
      value: yes

  #@ couldnot find on catalina 
  # - domain: "com.apple.safari"
  #   configures:
  #   - key: com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled
  #     type: bool
  #     value: true
  #   - key: IncludeDevelopMenu
  #     type: bool
  #     value: true
  #   - key: ShowFullURLInSmartSearchField
  #     type: bool
  #     value: true
  #   - key: AutoFillPasswords
  #     type: bool
  #     value: false
  #   - key: AutoOpenSafeDownlods
  #     type: bool
  #     value: false
  #   - key: DownloadsPath
  #     type: string
  #     value: ~/Dropbox/home/Downloads
  #   - key: ExtensionEnabled
  #     type: bool
  #     value: true
  #   - key: StatusMenuVisible
  #     type: bool
  #     value: false

  ## couldnot find on catalina
  # - domein: "com.apple.desktopservices"
  #   configures:
  #   - key: DSDontWriteNetworkStorse
  #     type: bool
  #     value: true

  # - domain: "com.apple.menuextra.battery"
  #   configures:
  #   - key: ShowPercent
  #     type: string
  #     value: YES

  - domain: "com.apple.menuextra.clock"
    configures:
    - key: DateFormat
      type: string
      value: "EEE MMM D  H:mm"
    - key: FlashDateSeparators
      type: bool
      value: no
    - key: IsAnalog
      type: bool
      value: no

  - domain: "com.apple.TextInputMenu"
    configures:
    - key: visible
      type: bool
      value: yes

  - domain: com.apple.repport
    configures:
    - key: familySyncedName
      type: string
      value: "SaltBook Pro"
